FROM --platform=linux/amd64 ruby:2.7.1-slim

# Copiamos el fichero details.rb al contenedor
COPY details.rb /opt/microservices/

# Exponemos el puerto 9080
EXPOSE 9080

# Ejecutamos el fichero details.rb al iniciar el contenedor
CMD ["ruby", "/opt/microservices/details.rb", "9080"]

# Comando para construir la imagen de details:
    # $ docker build -t details -f Dockerfile.details .
